### ISSUE TITLE
An option to show where the files will be moved, without actually moving files

### ISSUE THREAD

**Issue by uditarora** [ManrajGrover/organize-cli#27]
This would allow people to trust the application more, and should be fairly straightforward to do. Instead of executing the final 'mv' command, just output the command to the console.

**Comment by ManrajGrover** [comment]
Hi @uditarora, this sounds like a good feature. I'll have a look at the PR as soon as possible. Thank you for contributing! 😄

**Comment by uditarora** [comment]
Great!
Feel free to change things up. I did it the easiest way, without changing much code. There might be better ways of displaying the output though.
